variable "instance_type" {
  type    = string
  default = "t2.micro"
}

variable "name" {
  type    = string
  default = "sandbox-one"
}

variable "environment" {
  type    = string
  default = "test"
}

variable "project_name" {
  type    = string
  default = "sandbox"
}

variable "instance_count" {
  type    = number
  default = 2
}

variable "ami_id" {
  type    = string
  default = "ami-08edbb0e85d6a0a07"
}

variable "ami_key_pair_name" {
  type    = string
  default = "sandbox_id_rsa"
  #  default = generated_key_name.sandbox_id_rsa
}

/*
variable "generated_key_name" {
  type        = string
  default     = "sandbox_id_rsa"
  description = "Key-pair generated by Terraform"
}
*/